---
title: "Final Exam"
author: "Steven Todd McIntyre II"
format: 
  html:
    code-fold: true
    embed-resources: true
    df-print: paged
execute:
  warning: false

---
Dependencies
```{r}
library(tidyverse)
library(purrr)
library(httr)
library(jsonlite)
library(knitr)
library(kableExtra)
library(here)
library(rio)
library(lme4)
```

# (1) API calls to chess.com (10 points)

```{r}
response <- GET('https://api.chess.com/pub/country/US/players')

player_list <- fromJSON(rawToChar(response$content))$players

check_null <- function(val) {
  if(is.null(val)) {
    return(NA)
  }
  return(val)
}
#info <- GET('https://api.chess.com/pub/player/--untouchable--')
#fromJSON(rawToChar(info$content))

#stats <- GET('https://api.chess.com/pub/player/--untouchable--/stats')
#fromJSON(rawToChar(stats$content))

x <- tibble(username = player_list[1:500]) |>
  rowwise() |>
  mutate(
    info = list(
      fromJSON(
        rawToChar(
          GET(paste0('https://api.chess.com/pub/player/', username))$content
        )
      )
    ),
    stats = list(
      fromJSON(
        rawToChar(
          GET(paste0('https://api.chess.com/pub/player/', username, '/stats'))$content
        )
      )
    ),
    name                  = check_null(info$name),
    `number of followers` = check_null(info$followers),
    location              = check_null(info$location),
    last_online           = as_datetime(check_null(info$last_online)),
    rapid_last_rating     = check_null(stats$chess_rapid$last$rating),
    rapid_best_rating     = check_null(stats$chess_rapid$best$rating),
    rapid_record_win      = check_null(stats$chess_rapid$record$win),
    rapid_record_loss     = check_null(stats$chess_rapid$record$loss),
    rapid_record_draw     = check_null(stats$chess_rapid$record$draw)
  ) |>
  select(-info, -stats) 

x
```

# (2) Identify & Remove Duplicate Files (20 points)
```{r}
# make df to store duplicate file names
summ_deleted <- tibble(
  retained = character(),
  deleted_dup = character()
)

# find file names
file_names <- list.files(
  here("data"), 
  include.dirs = FALSE,
  recursive = TRUE,
  full.names = TRUE
)

# add content
file_contents <- tibble(file_names) |>
  rowwise() |>
  mutate(
    contents = list(import(file_names))
  ) |> 
  ungroup()

# find and record duplicates
# 
# i almost tried to learn how to use a hashmap for this for efficiency, but
# that's outside the scope of this class and, anyway, n=222 is pretty small
for(i in 1:length(file_contents$file_names)-1){
  for(j in (i+1):length(file_contents$file_names)){
    if(identical(file_contents$contents[i], file_contents$contents[j])) {
      summ_deleted <- summ_deleted |>
        add_row(
          retained = file_contents$file_names[i],
          deleted_dup = file_contents$file_names[j]
        )
    }
  }
}

map(summ_deleted$deleted_dup, file.remove)
summ_deleted
```

# (3) Multiple Models (10 points)
```{r}
benchmarks <- import(here("benchmarks.csv"))

# section borrowed from lab 2
benchmarks <- benchmarks |>
    as_tibble() |>
    mutate(wave = case_when(
                  season == "fall" ~ 0,
                  season == "winter" ~ 1,
                  season == "spring" ~ 2
                )
  )

slope_reliability <- benchmarks |>
  pivot_longer(cols = c("math", "reading"), names_to = "subject", values_to = "score") |>
  group_by(grade, subject) |>
  nest() |>
  mutate(
    tsv_mods = map(data, ~lmer(score ~ 1 + wave + (1+wave|sid), REML = FALSE, data=.x)),
    # this line adapted from Gemini with the prompt: "how to extract the variance of the slope; 
    # that is, the variance of the random effect of wave from a lme4 model"
    tsv = map_dbl(tsv_mods, ~VarCorr(.x)$sid["wave", "wave"]),
    osv = map_dbl(data, ~ {
      temp <- .x |>
        group_by(sid) |>
        nest() |>
        mutate(
          mods = map(data, ~lm(score ~ 1+ wave, data = .x)),
          coefs = map(mods, coef),
          slope = map_dbl(coefs, ~.x[["wave"]])
        )
      var(temp$slope)
        
    }),
    slope_reliability_estimate = tsv/osv
    
  )

slope_reliability |>
  select("grade", "subject", "slope_reliability_estimate")
```

# (4) Slope Reliability Function (10 points)
```{r}

get_sr <- function(lmer_mod) {
  df <- lmer_mod |>
    model.frame()
  
  # to generalize, I asked ChatGPT how retrieve the "wave", "score" and "sid" 
  # values from a generalized model object, assuming 1 slope and grouping factor:
  # https://chatgpt.com/share/6a25f818-d0b4-83e8-a19b-af4a05e11c65
  vc <- VarCorr(lmer_mod)[[1]] # assuming one grouping factor
  slope_name <- setdiff(rownames(vc), "(Intercept)") # or "wave" in our example
  resp_var <- all.vars(formula(lmer_mod))[1]  # or "score" in our example
  grouping_fact <- names(getME(lmer_mod, "flist")) # or "sid" in our example

  tsv <- vc[slope_name, slope_name]
  
  # chatGPT recommended doing this, since directly substituting
  # strings didn't work in the lm call below
  # https://chatgpt.com/share/6a25f818-d0b4-83e8-a19b-af4a05e11c65
  lm_f <- as.formula(paste0(resp_var, " ~ 1+ ", slope_name))
  
  osv_df <- df |>
    # asked ChatGPT how to group_by a string object's value:
    # https://chatgpt.com/share/6a25f818-d0b4-83e8-a19b-af4a05e11c65
    group_by(across(all_of(grouping_fact))) |> 
    nest() |>
    mutate(
      mods = map(data, ~lm(lm_f, data = .x)),
      coefs = map(mods, coef),
      slope = map_dbl(coefs, ~.x[[slope_name]])
    )
  
  osv <- var(osv_df$slope)

  return(tsv/osv)
}

test <- slope_reliability |>
  mutate(
    function_test_slope_reliability_estimate = map_dbl(tsv_mods, get_sr)
  ) |>
  select(
    "grade",
    "subject",
    "slope_reliability_estimate",
    "function_test_slope_reliability_estimate"
)

test
```

# (5) 95% Confidence Interval (CI) (20 points)
```{r}
# returns the slope reliability estimate (dbl), adapted from above
#
# df: a dataframe containing data to be analyzed
# grouping_var: string, name of grouping variable
# time_var: string, name of time variable
# outcome_var: string, name of outcome variable
get_sr2 <- function(df, grouping_var, time_var, outcome_var) {

  lmer_f <- as.formula(paste0(
    outcome_var,
    " ~ 1 + ",
    time_var,
    " + (1+",
    time_var,
    "|",
    grouping_var,
    ")"
  ))
  tsv_mod = lmer(lmer_f, REML = FALSE, data=df)
  vc <- VarCorr(tsv_mod)[[1]]
  tsv <- vc[time_var, time_var]
  
  # chatGPT recommended doing this, since directly substituting
  # strings didn't work in the lm call below
  # https://chatgpt.com/share/6a25f818-d0b4-83e8-a19b-af4a05e11c65
  lm_f <- as.formula(paste0(outcome_var, " ~ 1+ ", time_var))
  
  osv_df <- df |>
    # asked ChatGPT how to group_by a string object's value:
    # https://chatgpt.com/share/6a25f818-d0b4-83e8-a19b-af4a05e11c65
    group_by(across(all_of(grouping_var))) |> 
    nest() |>
    mutate(
      mods = map(data, ~lm(lm_f, data = .x)),
      coefs = map(mods, coef),
      slope = map_dbl(coefs, ~.x[[time_var]])
    )
  
  osv <- var(osv_df$slope)

  return(tsv/osv)

}

# much of the layout of make_df_sample and bootstrapper was recommended by 
# ChatGPT after essentially copying the part 5 prompt (initially, to help my 
# reading comprehension for the sample sizes)
# See prompts: https://chatgpt.com/share/6a264766-b060-83e8-86ac-026841d837be

# creates a single bootstrap sample df with data and sample-specific ids
# 
# df: the dataframe to make the sample from
# grouping_var: string, the grouping variable name 
make_df_sample <- function(df, grouping_var) {
  # get unique grouping_var values (sids)
  ids <- unique(df[[grouping_var]])
  
  # select a bootstrap sample of ids
  boot_ids <- sample(
    x = ids,
    size = length(ids),
    replace = TRUE
  )
  
  # return df with new sample-specific ids
  map2_dfr(
    boot_ids,
    seq_along(boot_ids),
    ~ {
      df |>
        filter(.data[[grouping_var]] == .x) |>
        mutate(boot_id = .y)
    }
  )
  
}

# function that returns a vector of slope reliability estimates
# for bootstrapped samples
#
# df: a dataframe containing data to be analyzed
# grouping_var: string, name of grouping variable
# time_var: string, name of time variable
# outcome_var: string, name of outcome variable
# n: int, number of bootstrap samples to take
bootstrapper <- function(df, grouping_var, time_var, outcome_var, n = 100) {

  
  boot_reliabilities <- map_dbl(
    1:n, 
    ~{
      boot_df <- make_df_sample(df, grouping_var)
      
      get_sr2(boot_df, "boot_id", time_var, outcome_var)
    }
  )
  
  boot_reliabilities
}

final_table <- slope_reliability |>
  mutate(
    boot_reliability_samples = map(
      data, 
      ~bootstrapper(.x, "sid", "wave", "score", n = 100)
    ),
    quantiles = map(
      boot_reliability_samples, 
      ~quantile(.x, probs = c(.025, .5, .975), na.rm = TRUE)
    ),
    n_size = map_dbl(data, ~length(unique(.x[["sid"]]))),
    CI_95_lower_bound = map_dbl(quantiles, ~.x[['2.5%']]),
    CI_95_upper_bound = map_dbl(quantiles, ~.x[['97.5%']]),
    median_sr_est     = map_dbl(quantiles, ~.x[['50%']])
  ) |>
  select(
    grade,
    subject,
    n_size,
    CI_95_lower_bound,
    CI_95_upper_bound,
    median_sr_est
  )

final_table

```



quantile function for part 5, .025, .95
